console.log("Avanzar");
console.log("Llenar 1");
console.log("Avanzar");
console.log("Avanzar");
console.log("Avanzar");
console.log("Llenar 1");
console.log("Avanzar");
console.log("Elimina 1");
console.log("Avanzar");
console.log("Elimina 1");
console.log("Avanzar");
